# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.10.dev0+gbbe482d.d20230321'
__version_tuple__ = version_tuple = (0, 1, 10, 'dev0', 'gbbe482d.d20230321')
