# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.8.dev5+gbc97d2a.d20230623'
__version_tuple__ = version_tuple = (0, 2, 8, 'dev5', 'gbc97d2a.d20230623')
