# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.7.dev4+g93b7405.d20230623'
__version_tuple__ = version_tuple = (0, 2, 7, 'dev4', 'g93b7405.d20230623')
